//====================================
//	Kyle Russell
//	jdamvc
//	Command
//====================================

package engine.core;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.text.MessageFormat;

//-----------------------------------
//            COMMAND
//-----------------------------------
//- map from listeners to object
//- holds command details as defined in listener
//- can call the className.methodName() method defined
//- commands are typically generated by their respective listener


public class Command
{
    private String commandName; //command input name, key etc
    private String[] paramTypes; //param type (class names) of the method
    private String className; //the class who holds the method to call
    private String methodName; //the method the command will call
    private String commandDescription; //brief command description - shown in help
    
    public Command(String commandName, String[] paramTypes, String className, String methodName, String commandDescription)
    {
        this.commandName        =   commandName;
        this.paramTypes         =   paramTypes;
        this.className          =   className;
        this.methodName         =   methodName;
        this.commandDescription =   commandDescription;
    }
    
    //Performs a call to the method methodName() of class className
    //params: argument values to be passed to the method 
    //instance: if you have an existing instance of the class pass it
    //otherwise call() will create a new instance 
    public Object call(String[] params, Object instance)
    {
        try
        {
            //Check param length matches from passed params and expected params
            if(params.length > paramTypes.length || params.length < paramTypes.length) throw new NoSuchMethodException();
            
            Class<?> viewClass  =   Class.forName(className);
            Method listenMethod;
            
            //Create new instance if no instance is passed
            if(instance == null)
                instance = viewClass.newInstance();
            
            //Method has params
            //invoke with passed params
            if(params.length > 0)
            {
                listenMethod =   viewClass.getMethod(methodName, Class.forName(paramTypes[0]));
                return listenMethod.invoke(instance, (Object[]) params);
            }
            
            //Method has no params, pass empty
            else
            {
                listenMethod    =   viewClass.getDeclaredMethod(methodName, new Class[]{});
                return listenMethod.invoke(instance);
            }
        }
        
        catch(ClassNotFoundException | NoSuchMethodException | IllegalAccessException | InvocationTargetException | InstantiationException e)
        {
            ExceptionOutput.output(e.getMessage(), ExceptionOutput.OutputType.DEBUG);
            return null;
        }
    }
    
    public String getCommandName()
    {
        return commandName;
    }
    
    public String getCommandDescription()
    {
        return commandDescription;
    }
    
    public String[] getParamTypes()
    {
        return paramTypes;
    }
    
    public String getClassName()
    {
        return className;
    }
    
    public String getMethodName()
    {
        return methodName;
    }
    
    public void setCommandName(String commandName)
    {
        this.commandName    =   commandName;
    }
    
    public void setCommandDescription(String commandDescription)
    {
        this.commandDescription =   commandDescription;
    }
    
    public void setParamTypes(String[] paramTypes)
    {
        this.paramTypes =   paramTypes;
    }
    
    public void setClassName(String className)
    {
        this.className  =   className;
    }
    
    public void setMethodName(String methodName)
    {
        this.methodName =   methodName;
    }
    
    
    @Override
    public String toString()
    {
        String output   =   MessageFormat.format("Command: {0}\nCommand class: {1}\nCommand method: {2}\nMethod param count: {3}\n", commandName, className, methodName, paramTypes[0]);
        return output;
    }
}
